### PR TITLE
Remove dependency on conversion package

### PR DESCRIPTION
**Pull request by andrewthad**

### CODE REVIEW

**Comment by andrewthad** [comment]
https://github.com/JustusAdam/mustache/issues/10

**Comment by JustusAdam** [comment]
Well ... this is going to be interesting ... Just this morning I sat down and also tried to remove the Conversion dependency. I'll merge your changes with mine locally, and hopefully that combined effort will yield a good result.

Don't be upset if I make a few changes, because I would like to enable ghc 7.8 compatibility again as well if I can pull it off.

**Comment by JustusAdam** [comment]
Thank you very much. Your way of solving this was much better than mine in some places. I used most of it unchanged.

**Comment by andrewthad** [comment]
Thanks!

**Comment by JustusAdam** [comment]
You can see your changes in the latest release as well.

**Pull request merged**
