### PR TITLE
Replace EitherT with ExceptT.

### PR DESCRIPTION
**Pull request by tmcgilchrist**
Needed to make this change for this project to compile with GHC 8.0.2.

Not entirely sure the existing `.travis.yml` will test out various versions of GHC.

### CODE REVIEW

**Comment by JustusAdam** [comment]
Thanks!

**Comment by tmcgilchrist** [comment]
Would you mind making a release for that on hackage?

**Comment by JustusAdam** [comment]
Done `2.3.0`

**Comment by tmcgilchrist** [comment]
Thanks

**Pull request merged**
